version: '3.4'

services:
  nesttest:
    image: nesttest
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
    depends_on:
      - mongodb
